### ISSUE TITLE
Current offset after nod results in offset of previously parsed value

### ISSUE THREAD

**Issue by ccreeten** [parsingdata/metal#204]
Example:
```java
Optional<Environment> parse = nod(1).parse(stream(1), enc());
CURRENT_OFFSET.eval(parse.get().order, enc()); // >Optional[0x00]
```
This is because now the current offset is based on the *current* of the ```ParseGraph```, and since ```nod``` introduces no value, we get the offset of a previous value. This is different from the offset of the environment of course, and different from the previous implementation. Is this by design?

I do believe this will be a non-issue when the lazy IO is implemented, and everything will be a ```Def``` anyway?

**Comment by jvdb** [comment]
I am aware of this change but it seems to be otherwise undocumented. The way the current offset is determined was changed because we didn't want `ValueExpression.eval()` to receive an `Environment` instance but only a `ParseGraph`. This was required in order to exclude `Environment` from equality checks on `Token`s and `ValueExpression`s. See #130 and #148.

It's true that once we have a nice lazy IO implementation that `Nod` will be removed, so this issue will then go away.

**Comment by jvdb** [comment]
I've added this issue as a note to #159. Closing this to prevent double issues.
