### ISSUE TITLE
Unexpected current offset behaviour while working with Sub

### ISSUE THREAD

**Issue by ccreeten** [parsingdata/metal#216]
Something popped up while @TheUnknownCylon was working on a Metal definition:
```java
static Token FORMAT =
    seq(
        sub(def("any", 1), con(0xFF)),
        def("none", CURRENT_OFFSET)
    );
```
In this example, we first parse a value at offset ```0xFF``` with a length of one.  When parsing the second ```none``` value, using the current offset as length, we are outside of the sub. So in this case we would expect the length to be 0 (and no value to be parsed), yet it is ```0x100```. 

This is because the new ```CURRENT_OFFSET``` implementation uses the last added value to the graph, and the definition of it is ```offset + length``` of the latest value added to the ```ParseGraph```, which in our case is the ```any``` value.

This seems like it should not be the case?

**Comment by jvdb** [comment]
I understand your surprise, because you are correct that the `def` is outside the `sub` so you would expect to have "returned" from the `sub` and then be back at offset=0. But it's defined behaviour exactly in the sense that you describe.

So we need to discuss whether having a real "current offset"-value is important enough to change the interface to `ValueExpression`. There's no other way to derive it reliably.
