### ISSUE TITLE
Self-referencing tokens can only be implemented using anonymous Token classes

### ISSUE THREAD

**Issue by rdvdijk** [parsingdata/metal#26]
The following 'self-referencing page' `Token` does not compile:

```java
private static final Token PAGE = 
    seq(
        def("pagePayload", 8),
        def("nextPageOffset", 4),
        sub(PAGE, ref("nextPageOffset")
    );
```

We cannot reference `PAGE` because we are defining it here.

To fix this, see the following workaround:

```java
private static final Token PAGE = new Token(null) {
    @Override
    protected ParseResult parseImpl(final String scope, final Environment env, final Encoding enc) throws IOException {
        return seq(
                def("pagePayload", 8),
                def("nextPageOffset", 4),
                sub(this, ref("nextPageOffset"))
        ).parse(scope, env, enc);
    }
};
```

Note the `sub(this, ...)` construct. This is a trick to reference back to the anonymous `PAGE` `Token` instance.

We need a way to express such a self-referencing token.

The main challenge in implementing such a token is that `Token`s are not aware of their 'parent' `Token`, so we can not locate it.

**Comment by rdvdijk** [comment]
An idea: Because we are talking about self-referencing `Token`s here, this means that the `Token` we want to parse again is present somewhere in the current `ParseGraph`, as the `definition` of some `ParseItem`. We could locate the `Token` in the `ParseGraph` and parse it.

To be honest, that sounds more like a workaround than anything else, but I think it could actually work.

**Comment by rdvdijk** [comment]
@jvdb As I commented at work: Another thing we could possibly do is change `String scope` to something like `List<Token>` scope, or `List<ParseItem>` scope.

Any other ideas?

**Comment by jvdb** [comment]
Things to consider:

1. How important is it to be able to reference `Token`s that were not successfully parsed before invocation of this `Token`? This means both forward references as well as backward references to `Token`s that failed. If the answer is that we can do without support for these cases, it will be relatively easy to implement since the `ParseGraph` from the `Environment` can be used to locate the required `Token`. I tend to think referencing previously and successfully parsed `Token`s is sufficient (at least in an initial implementation).
2. Should the `Token` itself appear in the `ParseGraph`? Normally I would say yes, but in this case, the `Token` only exists to work around a language limitation in Java, so it would make sense if that does not affect the resulting data structure.

**Comment by jvdb** [comment]
I ended up removing support for "relative names", since a `Token` itself never has a relative name, only its own name (so the approach would never work...) I suppose we could consider some kind of complex scheme where we start putting fully qualified names on all `ParseItem`s, but that seems unnecessary given what we're trying to solve with this functionality.
